/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var ocoParser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,7],$V1=[1,8],$V2=[1,9],$V3=[1,12],$V4=[1,13],$V5=[5,15,17,18,27,30,33],$V6=[1,21],$V7=[1,20],$V8=[1,19],$V9=[1,24],$Va=[1,25],$Vb=[1,29],$Vc=[1,30],$Vd=[1,32],$Ve=[1,34],$Vf=[1,35],$Vg=[28,31],$Vh=[5,15,17,18,27,29,30,33],$Vi=[1,49],$Vj=[15,19,28,33],$Vk=[1,59],$Vl=[1,58],$Vm=[1,66],$Vn=[31,36],$Vo=[15,27,30];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"expressions":3,"entries":4,"EOF":5,"entry":6,"entryname":7,"newlines":8,"block":9,"colorvalues":10,"reference":11,"metaname":12,"metablock":13,"metavalue":14,"NAME":15,":":16,"NUMBER":17,"HEXNUMBER":18,"=":19,"referenceNames":20,".":21,"metaentries":22,"metadata":23,"boolean":24,"colorvalue":25,"metanameparts":26,"/":27,"NEWLINE":28,"INDENT":29,"OUTDENT":30,",":31,"hexnum":32,"#":33,"(":34,"colorvaluevalues":35,")":36,"colorvaluevalue":37,"TRUE":38,"FALSE":39,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",15:"NAME",16:":",17:"NUMBER",18:"HEXNUMBER",19:"=",21:".",27:"/",28:"NEWLINE",29:"INDENT",30:"OUTDENT",31:",",33:"#",34:"(",36:")",38:"TRUE",39:"FALSE"},
productions_: [0,[3,2],[4,1],[4,2],[6,3],[6,3],[6,3],[6,3],[6,3],[6,2],[7,2],[7,2],[7,2],[11,2],[20,1],[20,3],[22,1],[22,2],[23,3],[23,4],[14,1],[14,1],[14,1],[14,1],[14,1],[12,2],[26,2],[26,3],[26,4],[26,3],[26,2],[8,1],[8,2],[9,3],[13,3],[10,1],[10,3],[32,1],[25,2],[25,2],[25,4],[35,1],[35,3],[37,1],[37,1],[24,1],[24,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
  return new yy.Entry('root', $$[$0-1], 'Root', _$[$0-1]) 
break;
case 2:
 this.$ = [ $$[$0] ]
break;
case 3:
 this.$ = $$[$0-1]; $$[$0-1].push($$[$0]); 
break;
case 4:
 this.$ = new yy.Entry($$[$0-2], $$[$0], null, _$[$0]); 
break;
case 5:
 this.$ = new yy.Entry($$[$0-2], $$[$0-1], 'Color', _$[$0-1]); 
break;
case 6:
 this.$ = new yy.Reference($$[$0-2], $$[$0-1])
break;
case 7:
 this.$ = new yy.Entry($$[$0-2], $$[$0], 'Metablock', _$[$0]); 
break;
case 8:
 this.$ = new yy.Metadata($$[$0-2], $$[$0-1]); 
break;
case 9:
 this.$ = $$[$0-1] 
break;
case 10: case 11: case 12: case 33:
 this.$ = $$[$0-1];
break;
case 13: case 14: case 20: case 22: case 23:
 this.$ = $$[$0]; 
break;
case 15:
 this.$ = $$[$0-2] + '.' + $$[$0] 
break;
case 16: case 35:
 this.$ = [$$[$0]] 
break;
case 17:
 this.$ = $$[$0-1]; this.$.push($$[$0]) 
break;
case 18:
 this.$ = new yy.Metadata($$[$0-2], $$[$0]);  
break;
case 19:
 this.$ = new yy.Metadata($$[$0-3], $$[$0-1]);  
break;
case 21:
 this.$ = parseFloat($$[$0]); 
break;
case 24:
 this.$ = new yy.Reference('metachild', $$[$0]); 
break;
case 25: case 34:
 this.$ = $$[$0-1]; 
break;
case 26:
 this.$ = '/' + $$[$0] 
break;
case 27: case 29:
 this.$ = $$[$0-2] + '/' + $$[$0] 
break;
case 28:
 this.$ = '/' + $$[$0-2] + '/' + $$[$0] 
break;
case 30:
 this.$ = $$[$0-1] + '/' 
break;
case 36:
 this.$ = $$[$0-2]; $$[$0-2].push($$[$0-1]); 
break;
case 37:
 this.$ = yytext; 
break;
case 38: case 39:
 this.$ = new yy.ColorValue('rgb', "#" + $$[$0]); 
break;
case 40:
 this.$ = new yy.ColorValue($$[$0-3], $$[$0-3] + "(" + $$[$0-1].join(",") + ")"); 
break;
case 41:
 this.$ = [$$[$0]]; 
break;
case 42:
 this.$ = $$[$0-2]; this.$.push($$[$0]); 
break;
case 45:
 this.$ = true; 
break;
case 46:
 this.$ = false; 
break;
}
},
table: [{3:1,4:2,6:3,7:4,10:6,12:5,15:$V0,17:$V1,18:$V2,25:11,26:10,27:$V3,33:$V4},{1:[3]},{5:[1,14],6:15,7:4,10:6,12:5,15:$V0,17:$V1,18:$V2,25:11,26:10,27:$V3,33:$V4},o($V5,[2,2]),{8:16,10:17,11:18,15:$V6,19:$V7,25:11,28:$V8,33:$V4},{8:22,11:28,14:23,15:$V9,17:$Va,19:$V7,24:26,25:27,28:$V8,33:$V4,38:$Vb,39:$Vc},{8:31,28:$V8,31:$Vd},{16:[1,33],27:$Ve,34:$Vf},{16:[1,36]},{16:[1,37]},{16:[1,38]},o($Vg,[2,35]),{15:[1,39]},{17:[1,41],18:[1,42],32:40},{1:[2,1]},o($V5,[2,3]),{9:43,29:[1,44]},{8:45,28:$V8,31:$Vd},{8:46,28:$V8},o($Vh,[2,31],{8:47,28:$V8}),{15:$Vi,20:48},{34:$Vf},{13:50,29:[1,51]},{8:52,28:$V8},{28:[2,20],34:$Vf},{28:[2,21]},{28:[2,22]},{28:[2,23]},{28:[2,24]},{28:[2,45]},{28:[2,46]},o($V5,[2,9]),{15:$V6,25:53,33:$V4},o($Vj,[2,10]),{15:[1,54],16:[2,30],26:55,27:$V3},{15:$Vk,17:$Vl,35:56,37:57},o($Vj,[2,11]),o($Vj,[2,12]),o([15,17,19,28,33,38,39],[2,25]),{16:[2,26],27:[1,60]},o($Vg,[2,38]),o($Vg,[2,39]),o($Vg,[2,37]),o($V5,[2,4]),{4:61,6:3,7:4,10:6,12:5,15:$V0,17:$V1,18:$V2,25:11,26:10,27:$V3,33:$V4},o($V5,[2,5]),o($V5,[2,6]),o($Vh,[2,32]),{28:[2,13]},{21:[1,62],28:[2,14]},o($V5,[2,7]),{12:65,15:$Vm,22:63,23:64,26:10,27:$V3},o($V5,[2,8]),o($Vg,[2,36]),{16:[2,27],27:$Ve},{16:[2,29]},{31:[1,68],36:[1,67]},o($Vn,[2,41]),o($Vn,[2,43]),o($Vn,[2,44]),{15:[1,70],26:69,27:$V3},{6:15,7:4,10:6,12:5,15:$V0,17:$V1,18:$V2,25:11,26:10,27:$V3,30:[1,71],33:$V4},{15:$Vi,20:72},{12:65,15:$Vm,23:74,26:10,27:$V3,30:[1,73]},o($Vo,[2,16]),{11:28,14:75,15:$V9,17:$Va,19:$V7,24:26,25:27,33:$V4,38:$Vb,39:$Vc},{16:[1,76],27:$Ve},o($Vg,[2,40]),{15:$Vk,17:$Vl,37:77},{16:[2,28]},{27:$Ve},o($V5,[2,33]),{28:[2,15]},o($V5,[2,34]),o($Vo,[2,17]),{8:78,28:$V8},{11:28,14:79,15:$V9,17:$Va,19:$V7,24:26,25:27,33:$V4,38:$Vb,39:$Vc},o($Vn,[2,42]),o($Vo,[2,18]),{8:80,28:$V8},o($Vo,[2,19])],
defaultActions: {14:[2,1],25:[2,21],26:[2,22],27:[2,23],28:[2,24],29:[2,45],30:[2,46],48:[2,13],55:[2,29],69:[2,28],72:[2,15]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = ocoParser;
exports.Parser = ocoParser.Parser;
exports.parse = function () { return ocoParser.parse.apply(ocoParser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}