/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var ocoParser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,7],$V1=[1,10],$V2=[1,11],$V3=[5,15,23,26,31],$V4=[1,19],$V5=[1,17],$V6=[1,22],$V7=[1,24],$V8=[1,26],$V9=[1,27],$Va=[24,28],$Vb=[5,15,23,25,26,31],$Vc=[1,39],$Vd=[1,49],$Ve=[1,48],$Vf=[1,55],$Vg=[28,35],$Vh=[15,23,26];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"expressions":3,"entries":4,"EOF":5,"entry":6,"entryname":7,"newlines":8,"block":9,"colorvalues":10,"reference":11,"metaname":12,"metablock":13,"metavalue":14,"NAME":15,":":16,"=":17,"referenceNames":18,".":19,"metaentries":20,"metadata":21,"metanameparts":22,"/":23,"NEWLINE":24,"INDENT":25,"OUTDENT":26,"colorvalue":27,",":28,"hexnum":29,"HEXNUMBER":30,"#":31,"NUMBER":32,"(":33,"colorvaluevalues":34,")":35,"colorvaluevalue":36,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",15:"NAME",16:":",17:"=",19:".",23:"/",24:"NEWLINE",25:"INDENT",26:"OUTDENT",28:",",30:"HEXNUMBER",31:"#",32:"NUMBER",33:"(",35:")"},
productions_: [0,[3,2],[4,1],[4,2],[6,3],[6,3],[6,3],[6,3],[6,3],[6,2],[7,2],[11,2],[18,1],[18,3],[20,1],[20,2],[21,4],[21,4],[12,2],[14,1],[22,2],[22,3],[22,4],[22,3],[22,2],[8,1],[8,2],[9,3],[13,3],[10,1],[10,3],[29,1],[27,2],[27,2],[27,4],[34,1],[34,3],[36,1],[36,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
  return new yy.Block('root', $$[$0-1], 'Root', _$[$0-1]) 
break;
case 2:
 this.$ = [ $$[$0] ]
break;
case 3:
 this.$ = $$[$0-1]; $$[$0-1].push($$[$0]); 
break;
case 4:
 this.$ = new yy.Block($$[$0-2], $$[$0], null, _$[$0]); 
break;
case 5:
 this.$ = new yy.Block($$[$0-2], $$[$0-1], 'Color', _$[$0-1]); 
break;
case 6:
 this.$ = new yy.Reference($$[$0-2], $$[$0-1])
break;
case 7:
 this.$ = new yy.Block($$[$0-2], $$[$0], 'Metadata', _$[$0]); 
break;
case 8:
 this.$ = new yy.Metadata($$[$0-2], $$[$0-1]); 
break;
case 9:
 this.$ = $$[$0-1] 
break;
case 10: case 27:
 this.$ = $$[$0-1];
break;
case 11: case 19:
 this.$ = $$[$0]; 
break;
case 12: case 31:
 this.$ = yytext; 
break;
case 13:
 this.$ = $$[$0-2] + '.' + $$[$0] 
break;
case 14: case 29:
 this.$ = [$$[$0]] 
break;
case 15:
 this.$ = $$[$0-1]; this.$.push($$[$0]) 
break;
case 16: case 17:
 this.$ = new yy.Metadata($$[$0-3], $$[$0-1]);  
break;
case 18: case 28:
 this.$ = $$[$0-1]; 
break;
case 20:
 this.$ = '/' + $$[$0] 
break;
case 21: case 23:
 this.$ = $$[$0-2] + '/' + $$[$0] 
break;
case 22:
 this.$ = '/' + $$[$0-2] + '/' + $$[$0] 
break;
case 24:
 this.$ = $$[$0-1] + '/' 
break;
case 30:
 this.$ = $$[$0-2]; $$[$0-2].push($$[$0-1]); 
break;
case 32: case 33:
 this.$ = new yy.ColorValue('rgb', "#" + $$[$0]); 
break;
case 34:
 this.$ = new yy.ColorValue($$[$0-3], $$[$0-1].join(",")); 
break;
case 35:
 this.$ = [$$[$0]]; 
break;
case 36:
 this.$ = $$[$0-2]; this.$.push($$[$0]); 
break;
}
},
table: [{3:1,4:2,6:3,7:4,10:6,12:5,15:$V0,22:8,23:$V1,27:9,31:$V2},{1:[3]},{5:[1,12],6:13,7:4,10:6,12:5,15:$V0,22:8,23:$V1,27:9,31:$V2},o($V3,[2,2]),{8:14,10:15,11:16,15:$V4,17:[1,18],24:$V5,27:9,31:$V2},{8:20,14:21,15:$V6,24:$V5},{8:23,24:$V5,28:$V7},{16:[1,25],23:$V8,33:$V9},{16:[1,28]},o($Va,[2,29]),{15:[1,29]},{29:30,30:[1,32],32:[1,31]},{1:[2,1]},o($V3,[2,3]),{9:33,25:[1,34]},{8:35,24:$V5,28:$V7},{8:36,24:$V5},o($Vb,[2,25],{8:37,24:$V5}),{15:$Vc,18:38},{33:$V9},{13:40,25:[1,41]},{8:42,24:$V5},{24:[2,19]},o($V3,[2,9]),{15:$V4,27:43,31:$V2},o([15,17,24,31],[2,10]),{15:[1,44],16:[2,24],22:45,23:$V1},{15:$Vd,32:$Ve,34:46,36:47},o([15,16,24],[2,18]),{16:[2,20],23:[1,50]},o($Va,[2,32]),o($Va,[2,33]),o($Va,[2,31]),o($V3,[2,4]),{4:51,6:3,7:4,10:6,12:5,15:$V0,22:8,23:$V1,27:9,31:$V2},o($V3,[2,5]),o($V3,[2,6]),o($Vb,[2,26]),{24:[2,11]},{19:[1,52],24:[2,12]},o($V3,[2,7]),{12:56,15:$Vf,20:53,21:54,22:8,23:$V1},o($V3,[2,8]),o($Va,[2,30]),{16:[2,21],23:$V8},{16:[2,23]},{28:[1,58],35:[1,57]},o($Vg,[2,35]),o($Vg,[2,37]),o($Vg,[2,38]),{15:[1,60],22:59,23:$V1},{6:13,7:4,10:6,12:5,15:$V0,22:8,23:$V1,26:[1,61],27:9,31:$V2},{15:$Vc,18:62},{12:56,15:$Vf,21:64,22:8,23:$V1,26:[1,63]},o($Vh,[2,14]),{16:[1,65],23:$V8},{16:[1,66]},o($Va,[2,34]),{15:$Vd,32:$Ve,36:67},{16:[2,22]},{23:$V8},o($V3,[2,27]),{24:[2,13]},o($V3,[2,28]),o($Vh,[2,15]),{14:68,15:$V6},{14:69,15:$V6},o($Vg,[2,36]),{8:70,24:$V5},{8:71,24:$V5},o($Vh,[2,16]),o($Vh,[2,17])],
defaultActions: {12:[2,1],22:[2,19],38:[2,11],45:[2,23],59:[2,22],62:[2,13]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = ocoParser;
exports.Parser = ocoParser.Parser;
exports.parse = function () { return ocoParser.parse.apply(ocoParser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}